"""create movie table

Revision ID: 546b31e958c7
Revises: 
Create Date: 2026-04-13 20:51:40.007586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '546b31e958c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('poster', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movies')
    # ### end Alembic commands ###
